#!/bin/zsh

if [  $# -ne 1 ]; then
	unset CHAIN CHAIN_NAME RPC_URL EXPLORER_URL EXPLORER_API_KEY FOUNDRY_ETH_RPC_URL VERIFIER_URL ETHERSCAN_API_KEY
else
	c=$(getchain $1)

	export CHAIN=$(echo $c | jq -rj '.id')
	export CHAIN_NAME=$(echo $c | jq -rj '.name')
	export RPC_URL=$(echo $c | jq -rj '.rpc')
	export EXPLORER_URL=$(echo $c | jq -rj '.explorer')
	export EXPLORER_API_KEY=$(echo $c | jq -rj '.explorerKey')

	export FOUNDRY_ETH_RPC_URL=$RPC_URL
	export VERIFIER_URL=$EXPLORER_URL
	export ETHERSCAN_API_KEY=$EXPLORER_API_KEY
fi
