#!/bin/zsh
set -euo pipefail

chainId=$1
owner=$2

pair=$3
farm=$4

unset ETH_KEYSTORE_ACCOUNT
source setchain $chainId

# call "exit()" to withdraw

lpBalance=$(cast call $farm "balanceOf(address)(uint256)" $owner | sed -n "1p" | cut -d " " -f1)
defi uni2 $chainId $owner $pair --balance $lpBalance

